//
//  MMADPayPaymentModelParams.h
//  Pods
//
//  Created by Vashum on 06/12/16.
//
//

#import <Foundation/Foundation.h>
#import "MMADPayHashes.h"

@interface MMADPayPaymentModelParams : NSObject

///----------------------------------
/// @name MMADPay Gateway parameters
///----------------------------------



///----------------------------------
/// @name Mandatory
///----------------------------------


/**
 Pay ID  is provided by Mmadpay .Max character: 16 and Min character: 16 e.g., 160234578452178
 */
@property (strong, nonatomic) NSString *payID;

/**
Merchant reference number to be generated from app.Max character: 50  and Min character: 1 e.g., ESN78452
*/

@property (strong, nonatomic) NSString *orderID;


/**
 Url of merchant website to get the response  back after transaction is done. Max character: 1024 and Min character: 5 e.g.,http://www.response.com
 */
@property (strong, nonatomic) NSString *returnURL;


/**
 Type of transaction. Either SALE/AUTH
 */
@property (strong, nonatomic) NSString *taxType;

/**
 Unique value generated by SHA 256 hashing algorithm. Max character: 64 and Min character: 64 e.g., 7995156CE4C40C44C41BECA3B9CE09B9
 */
@property (strong, nonatomic) NSString *hashKey;

///----------------------------------
/// @name Optional
///----------------------------------

/**
 Name of the customer. Max character: 150 and Min character: 1 e.g., Johnson Pal
 */
@property (strong, nonatomic) NSString *customerName;


/**
 First name of the customer. Max character: 150 and Min character: 1 e.g., Johnson
 */
@property (strong, nonatomic) NSString *customerFirstName;

/**
 Last name of the customer. Max character: 150 and Min character: 1 e.g.,  Pal
 */

@property (strong, nonatomic) NSString *customerLastName;

/**
 Customer address. Max character: 250 and Min character: 2 e.g., House no-101
 */
@property (strong, nonatomic) NSString *customerStreeAddress1;
/**
 Customer city.
 */
@property (strong, nonatomic) NSString *customerCity;
@property (strong, nonatomic) NSString *customerState;
@property (strong, nonatomic) NSString *customerCountry;
@property (strong, nonatomic) NSString *customerZip;
@property (strong, nonatomic) NSString *customerPhone;
@property (strong, nonatomic) NSString *customerEmail;
@property (strong, nonatomic) NSString *custShippingLastName;
@property (strong, nonatomic) NSString *customerShippingFirstName;
@property (strong, nonatomic) NSString *customerShippingName;
@property (strong, nonatomic) NSString *customerShippingStreetAddress1;
@property (strong, nonatomic) NSString *customerShippingStreetAddress2;
@property (strong, nonatomic) NSString *customerShippingCity;
@property (strong, nonatomic) NSString *customerShippingState;
@property (strong, nonatomic) NSString *customerShippingCountry;
@property (strong, nonatomic) NSString *customerShippingZip;
@property (strong, nonatomic) NSString *customerShippingPhone;
@property (strong, nonatomic) NSString *amount;
@property (strong, nonatomic) NSString *currencyCode;
@property (strong, nonatomic) NSString *productDescription;

@property (strong, nonatomic) NSString *merchantName;

+ (MMADPayPaymentModelParams*)initialiseParametersWithPostData: (NSDictionary*)postParam;

@end
